### ISSUE TITLE
DTB last_comp_version issue

### ISSUE THREAD

**Issue by ppeetteerrs** [diodesign/devicetree#2]
The binary at https://github.com/diodesign/diosix/tree/binaries/diosix is not updated to incorporate commit #741784b. Default dtb compiled using dtc causes an error while booting.

**Comment by diodesign** [comment]
Hi -- thanks for the nudge, it's appreciated. I've generated a new binary and pushed it to the Diosix `binaries` branch: diodesign/diosix@807431896136196057a662a58350739e928ad9fe 

This runs with Qemu 5.2.0 (Debian 1:5.2+dfsg-9) for me:

```
qemu-system-riscv64 -bios none -nographic -machine virt -smp 2 -m 1G -kernel diosix-0.0.2-debug-20210404
```

Closing issue as I think that's fixed, then.
